export const guides = [
  {
    id: 1,
    slug: 'chatgpt-monthly-closing-checklist',
    title: 'ChatGPT로 월별 결산 체크리스트 자동화하기',
    excerpt: '77개 항목의 결산 체크리스트를 Notion DB로 옮기고 AI로 진행률을 관리하는 방법',
    category: '결산',
    readTime: '8분',
    date: '2026.04.15',
    tags: ['ChatGPT', 'Notion', '결산'],
    content: `## 배경\n\n월별 결산은 반복 작업의 연속입니다...`,
  },
  {
    id: 2,
    slug: 'executive-report-one-pager-prompt',
    title: '임원보고서 원페이저, 프롬프트 하나로 끝내기',
    excerpt: '날것의 메모를 C레벨 의사결정 문서로 변환하는 프롬프트 템플릿',
    category: '보고서',
    readTime: '12분',
    date: '2026.04.10',
    tags: ['Claude', '보고서', '프롬프팅'],
    content: `## 개요\n\nC레벨 임원은 핵심만 원합니다...`,
  },
  {
    id: 3,
    slug: 'ifrs18-transition-ai-analysis',
    title: 'IFRS 18 전환, AI로 영향 분석 초안 잡기',
    excerpt: '현재 계정과목 체계를 새 기준에 매핑하는 실무 프로세스',
    category: '결산',
    readTime: '15분',
    date: '2026.04.02',
    tags: ['IFRS18', '기준서', '영향분석'],
    content: `## IFRS 18이란\n\n2027년부터 적용되는 새로운 손익계산서 기준...`,
  },
  {
    id: 4,
    slug: 'audit-evidence-review-automation',
    title: '감사증빙 1차 검토, Claude로 반자동화하기',
    excerpt: '수백 건의 증빙을 AI가 먼저 분류하고, 사람은 예외만 검토하는 워크플로우',
    category: '감사',
    readTime: '10분',
    date: '2026.03.25',
    tags: ['Claude', '감사', '증빙검토'],
    content: `## 문제 정의\n\n감사 시즌마다 쏟아지는 증빙 검토...`,
  },
  {
    id: 5,
    slug: 'tax-adjustment-review-rpa',
    title: '세무조정계산서 검토 RPA + AI 파이프라인',
    excerpt: 'RPA로 ERP에서 데이터를 뽑고, AI로 검토 포인트를 잡는 2단계 자동화',
    category: 'RPA',
    readTime: '18분',
    date: '2026.03.15',
    tags: ['RPA', '세무조정', '법인세'],
    content: `## 전체 파이프라인 개요\n\n...`,
  },
  {
    id: 6,
    slug: 'vendor-selection-rfp-automation',
    title: '감사법인 선정 RFP, AI로 비교표 자동 생성',
    excerpt: '4개 법인 제안서를 AI가 구조화하고 한 장짜리 비교표로 만드는 방법',
    category: '감사',
    readTime: '9분',
    date: '2026.03.05',
    tags: ['RFP', '감사법인', 'Big4'],
    content: `## 배경\n\n감사법인 선정은 3~4년 주기의 큰 의사결정...`,
  },
];

export const cases = [
  {
    id: 1,
    slug: 'daewon-pharma-rfp-automation',
    company: '대원제약',
    industry: '제약',
    title: '감사법인 선정 RFP 4사 비교표 자동화',
    impact: '작업 시간 8시간 → 1시간',
    author: '김덕준 재무팀장',
    tags: ['RFP', '벤더선정', 'Big4'],
    publishedAt: '2026.04.18',
    content: `...`,
  },
  {
    id: 2,
    slug: 'anonymous-manufacturer-revenue-recognition',
    company: '익명 제조사',
    industry: '제조',
    title: '매출 인식 시점 검토 파이프라인 구축',
    impact: '월 80건 리뷰 자동 1차 스크리닝',
    author: '이○○ 회계팀장',
    tags: ['매출인식', 'IFRS15'],
    publishedAt: '2026.04.12',
    content: `...`,
  },
  {
    id: 3,
    slug: 'anonymous-it-tax-adjustment',
    company: '익명 IT기업',
    industry: 'IT',
    title: '세무조정계산서 검토 보조 시스템',
    impact: '조정 오류 사전 적발률 40% 개선',
    author: '박○○ 세무팀 과장',
    tags: ['세무조정', '법인세'],
    publishedAt: '2026.04.05',
    content: `...`,
  },
  {
    id: 4,
    slug: 'anonymous-retail-inventory-valuation',
    company: '익명 유통사',
    industry: '유통',
    title: '재고자산 평가 손실 산정 자동화',
    impact: '분기 결산 리드타임 3일 단축',
    author: '최○○ 재무팀 차장',
    tags: ['재고자산', '평가손실'],
    publishedAt: '2026.03.28',
    content: `...`,
  },
];

export const categories = ['전체', '결산', '보고서', '세무', '감사', 'RPA', '프롬프팅'];
export const industries = ['전체', '제약', '제조', 'IT', '유통', '금융'];
